var types = {
  DEFAULT: 'DEFAULT',
  RECOMMEND_MOMENTS: 'RECOMMEND_MOMENTS',
  DISPLAY_PUBLISH_MOMENT_COMP: 'DISPLAY_PUBLISH_MOMENT_COMP',
  MY_CIRCLE_LIST: 'MY_CIRCLE_LIST',
  MY_MOMENT_LIST: 'MY_MOMENT_LIST',
  MY_BLOG_LIST: 'MY_BLOG_LIST',
  MY_QUESTION_LIST: 'MY_QUESTION_LIST',
  USER_MOMENT_LIST: 'USER_MOMENT_LIST',
  USER_BLOG_LIST: 'USER_BLOG_LIST',
  USER_QUESTION_LIST: 'USER_QUESTION_LIST',
  BLOG_DETAIL: 'BLOG_DETAIL',
  LOGIN_USER_INFO: 'LOGIN_USER_INFO',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_INFO: 'USER_INFO',
  ABOUT_ME_LIST: 'ABOUT_ME_LIST',
  FOLLOW_USER: 'FOLLOW_USER',
  FOLLOW_LIST: 'FOLLOW_LIST',
  SEARCH_RESULT_LIST: 'SEARCH_RESULT_LIST'
}
export default types
