var types = {
  DEFAULT: 'DEFAULT',
  RECOMMEND_MOMENTS: 'RECOMMEND_MOMENTS',
  DISPLAY_PUBLISH_MOMENT_COMP: 'DISPLAY_PUBLISH_MOMENT_COMP',
  FETCH_MY_CIRCLE_LIST: 'FETCH_MY_CIRCLE_LIST',
  FETCH_MY_MOMENT_LIST: 'FETCH_MY_MOMENT_LIST',
  FETCH_MY_BLOG_LIST: 'FETCH_MY_BLOG_LIST'
}
export default types
